name: Docker Image CI

on:
  push:
    branches: ['dev']
  pull_request:
    branches: ['dev']

jobs:
  build:
    name: Docker build
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build website image
        run: |
          docker build --platform linux --tag jhhg04/sitio001:latest -f src/Dockerfile .
      - name: Publish website image
        run: |
          docker push jhhg04/sitio001:latest
  deploy:
    name: Web App deploy
    needs:
      - build
    runs-on: ubuntu-latest
    steps:
      - name: App service auth
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'jhhg04sitio001'
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          images: 'jhhg04/sitio001:latest'
